# A workflow to create the Cyphal Specification PDF

name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF file using LaTeX

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run texer container
      uses: docker://ghcr.io/opencyphal/texer:te22.4.1
      with:
        entrypoint: /bin/bash
        args: >
          -c "
          git config --global --add safe.directory '*'    &&
          pip install -U setuptools                       &&
          pip install -r requirements.txt                 &&
          ./compile.sh
          "

    - name: Upload pdf as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Cyphal Specification
        path: specification/Cyphal_Specification.pdf
        if-no-files-found: error

    - name: Upload diagnostic snapshot
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: workspace-${{github.job}}
        path: '*'
        retention-days: 3

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: specification/
  deploy:
    environment:
      name: github-pages
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
